### ISSUE TITLE
Issue with the demo website project?

### ISSUE THREAD

**Issue by john-yick** [rohit-gohri/redocusaurus#111] opened 2022-01-14 03:29 UTC
I just downloaded the code from the website and it seems to have a bad reference where it cannot find a module

![image](https://user-images.githubusercontent.com/17866270/149446632-3631357d-1012-4c39-9b64-b7e55d27c497.png)

**Comment by rohit-gohri** [comment] 2022-01-14 04:11
Did you use `yarn` for setting up the node_modules?

**Comment by john-yick** [comment] 2022-01-14 06:41
So I set it up with npm. Do you need yarn to make it all work?

**Comment by rohit-gohri** [comment] 2022-01-14 07:06
The demo project needs `yarn` since it is using `workspaces` as the project is setup as a monorepo. There is more info in https://github.com/rohit-gohri/redocusaurus/blob/main/DEVELOPMENT.md, but lerna is no longer used. Everything is through `yarn` now

**Comment by rohit-gohri** [comment] 2022-01-24 09:15
This seems to be an issue with a change in API in latest version of docusaurus, #116 has more details. Closing in favour of that.
Duplicate of #116

**Closed by rohit-gohri** 2022-01-24 09:15 UTC
