### ISSUE TITLE
Multiple APIs?

### ISSUE THREAD

**Issue by Anthony-Gaudino** [rohit-gohri/redocusaurus#108] opened 2021-12-12 14:11 UTC
Is it possible to have multiple APIs like https://github.com/cloud-annotations/docusaurus-plugin-openapi#multiple-openapi-definitions allows?

What we would like to have is menu entries in Docusaurus, each pointing to the documentation of an API (Redoc).
Is this possible with Redocusaurus? Like defining multiple plugin entries?

Also we need to specify the URL of each API, for example, https://localhost:8080, https://localhost:8081 ...
We would use it for documentation and hopefully with https://github.com/wll8/redoc-try to allow developers to try each API.

**Comment by rohit-gohri** [comment] 2022-01-21 19:13
> Is it possible to have multiple APIs

Yes, you can pass an array of options to redocusaurus to render them all on different pages. Though this doesn't work with sidebar you need to use menu bars or dropdowns to navigate b/w them (see #91)

> Also we need to specify the URL of each API
I think that should be defined in the openapi spec itself.

> hopefully with wll8/redoc-try

Not sure if that will work with this. But you can try, it'll great if you can add a guide to the docs if it works out!

Closing this, since this is a duplicate of #91.

**Closed by rohit-gohri** 2022-01-21 19:13 UTC
Labels: duplicate
